Updated Kernel conversion methods
ruby/rbs pull request #1445
Opened 2023-08-19 22:10 UTC by sampersand

This is a merging of the previous individual PRs for conversion methods into one, larger PR. (#1433 , #1434, #1435, #1436, #1437, #1438, #1439). Look at them for a little more in-depth details, adn some discussion topics. Summary of changes is below:

- `Kernel#Array`: Updated to represent the true definition: Only `.to_ary` and `.to_a` are used for conversions, and everything else is boxed up in an array.
- `Kernel#Complex`: Added the `.to_c` variant.
- `Kernel#Float`: Changed from `Numeric | String` to just be `_ToF`, which is what's used `internally.
- `Kernel#Hash`: The argument is no longer an `Object`: Instead, `.to_hash` is required for its argument, with the special case of `nil` and empty arrays (and _only_ empty arrays) returning empty hashes.
- `Kernel#Integer`: Updated to reflect the ability to pass implicit `.to_str` and `.to_int` to all variants, and only `.to_i` (not being a subclass of `Numeric`) for the one-argument case
- `Kernel#Rational`: Oh boy, this method is a mess. Check out the [original issue](https://github.com/ruby/rbs/pull/1438) for more details. tl;dr: If the first argument isn't `_ToInt | _ToR`, but is `Numeric`, it attempts to do division with it, which allows for returning arbitrary types.
- `Kernel#String`: Simply cleaned up naming; it was semantically correct beforehand.

For all conversion methods with an `exception: bool` field, two variants have been added: `(..., ?exception: true) -> type` and `(..., exception: bool) -> type?`. This reflects the fact that with `exception: false` (or an unknown boolean value, which may be false), the return type is `nil`.

Additionally, all the `exception: bool` variants, when given invalid types but with `exception: false`, will return `nil`. That's also been accounted for.

2023-08-20 00:22 UTC, ParadoxV5 commented on core/kernel.rbs
> +  def self?.Hash: [K, V] (nil | [] _empty) -> Hash[K, V]
`nil` and `[]` are already `_ToHash[untyped, untyped]`s. But if you want to add them here explicitly, note the `[K, V]` are unused.

```suggestion
  def self?.Hash: (nil | [] _empty) -> Hash[untyped, untyped]
```

2023-08-21 16:03 UTC, ParadoxV5 commented on core/kernel.rbs
> +  def self?.Hash: [K, V] (nil | [] _empty) -> Hash[K, V]
Oh right they aren’t `_ToHash`es, just `_ToH`s.
So this method only checks for `#to_hash` but not `#to_h`, unlike `Integer` and `Array`?

2023-08-22 00:43 UTC, soutaro commented on core/kernel.rbs
> +  interface _RationalDiv[T]
Need a new line before `_RationalDiv`.

2023-08-22 00:43 UTC, soutaro requested changes
Looks good. Some newline problems to make the CI pass.

2023-08-22 01:46 UTC, soutaro approved these changes
I will take a look at the CI fails.

2023-08-22 02:00 UTC, merged