[socket] Add RBS file for "socket"
ruby/rbs pull request #699
Opened 2021-07-01 14:59 UTC by HoneyryderChuck

Added RBS signatures for the "socket" package (no tests).

2021-07-04 15:04 UTC, soutaro commented on core/socket.rbs
> +  #     sock.setsockopt(Socket::Option.bool(:INET, :SOCKET, :REUSEADDR, true))
> __[Goodcheck]__ Prefer `boolish` over `bool` for method arguments and block return values ([view](https://sider.review/gh/repos/174796313/pulls/699#issue-5728785))
>
> <details>
>
> See the doc below:
> https://github.com/ruby/rbs/blob/78d04a2db0f1c4925d2b13c2939868edf9465d6c/docs/syntax.md#bool-or-boolish
>
> | Rule |
> | ---- |
> | `rbs.prefer_boolish` |
>
> You can [close this issue](https://sider.review/gh/repos/174796313/pulls/699#issue-5728785) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

This is a false detection. Closing.

2021-07-04 15:18 UTC, soutaro requested changes
I really appreciate this great work! 🙏 

I want to ask you to change the file name.

* Could you move the file under `stdlib/socket/0` directory, because `socket` is not built-in?
* How about splitting files for each classes, like `basic_socket.rbs`, `socket.rbs`, ...? (This is optional but would make reading and future updates easier.)

2021-07-04 15:18 UTC, soutaro commented on core/socket.rbs
> +  def __recv_nonblock: (untyped, untyped, untyped, untyped) -> untyped
👍

2021-07-04 23:12 UTC, HoneyryderChuck commented on core/socket.rbs
> +  def __recv_nonblock: (untyped, untyped, untyped, untyped) -> untyped
fine to leave it as is, I suppose? :)

2021-07-04 23:12 UTC, HoneyryderChuck commented
@soutaro thx. Just committed the changes you proposed. hope it's fine.

2021-07-05 02:30 UTC, soutaro commented on core/socket.rbs
> +  def __recv_nonblock: (untyped, untyped, untyped, untyped) -> untyped
Yes. It's fine to leave the defs here.

2021-07-05 02:31 UTC, soutaro approved these changes
Thank you so much! 👍

2021-07-05 02:32 UTC, merged

2022-09-03 13:49 UTC, tisonkun commented on stdlib/socket/0/socket.rbs
> +  def initialize: (Symbol domain, Symbol socktype, ?Integer protocol) -> untyped
It seems we can write `socket = Socket.new(Socket::AF_INET, Socket::SOCK_STREAM, 0)` where the parameters are `Integer`?