Add Recursiive type alias defnition validation
ruby/rbs pull request #719
Opened 2021-07-17 17:12 UTC by raosush

# Description
- Implemented validation for recursive type alias
- Added a `RecursiveTypeAliasError` class
- Added signatures for `RecursiveTypeAliasError`
- Added a test to validate the funcitoning of `RecursiveTypeAliasError`

# Example
![image](https://user-images.githubusercontent.com/57192414/126044665-96c6d9aa-f62d-4ffa-b3ff-d52374c20302.png)

Fixes: #687

Signed-off-by: Sushanth Sathesh Rao <rao.sush004@gmail.com>

2021-07-17 17:17 UTC, raosush commented
# Suggestion
* The current code raises `LoadingError` if & only if the assigned type is an alias & is the same as the one it is being assigned to
* The implementation could be changed to raise an exception whenever the type being assigned to an alias is again an alias, because I do not seem to find any use case of aliasing an aliased type

2021-07-18 03:53 UTC, raosush commented
- [ ] Implement recursive type alias validation for `RBS::Types::Union` and `RBS::Types::Intersection`

2021-07-18 10:19 UTC, soutaro commented
Thank you @raosush, but I don't think this is the best way to implement the validation. We can discuss this later.

2021-07-25 14:40 UTC, soutaro commented on test/validator_test.rb
> +  def test_validate_recursive_type_alias
Please include assertions to let us know which `type` declaration is prohibited/allowed.

2021-07-27 02:08 UTC, soutaro commented on lib/rbs/definition_builder.rb
> +      strongly_connected_components = TSort.strongly_connected_components(each_node, each_child)
I don't think building strongly connected components is necessary.
We can build the transitive closure of dependencies from type name. And test if the left hand side is included in the closure. I believe the definition with transitive closure is more straightforward.

1. Define _dependent type names_ for given type `T` (`DD(T)`) same as `extract_type_aliases`.
2. Calculate transitive closure of _dependent type names_ (`D(T)`) of one type.
3. Test if the type alias definition `type t = S` includes a circular reference by `D(S) ∋ t`.

On the other hand, I'm not very sure if which one is faster.

2021-07-27 02:15 UTC, soutaro commented
We can define a class to calculate dependencies between types like `TypeAliasDependency` that:

```rbs
class TypeAliasDependency
  attr_reader env: Environment

  attr_reader direct_dependencies: Hash[Types::t, Set[TypeName]]    # Cache calculated dependencies for performance
  attr_reader dependencies: Hash[Types::t, Set[TypeName]]
  
  def initialize: (env: Environment) -> void

  # Returns true if type alias declaration of `alias_name` is circular and prohibited.
  #
  def circular_definition?: (TypeName alias_name) -> bool

  private

  def direct_dependency: (Types::t) -> Set[TypeName]       # Utility methods to calculate dependencies
  def dependency: (Types::t) -> Set[TypeName]
end
```

This is an example to illustrate my idea, and you would need to revise the detail of the API.

2021-07-27 02:15 UTC, soutaro commented on test/validator_test.rb
> +  def test_validate_recursive_type_alias
All of the examples are prohibited ones. 👍

2021-07-27 02:17 UTC, soutaro commented on lib/rbs/errors.rb
> +    def self.check!(entry:, scc:, scc_hash:)
Looks better to implement the test in `Validator` class for this case.

2021-07-27 02:17 UTC, soutaro commented on sig/errors.rbs
> +    attr_reader defs: Array[TypeName]
Rename to `alias_names`.

2021-07-27 02:18 UTC, soutaro requested changes
@raosush Posted comments!

2021-07-31 05:43 UTC, soutaro commented on lib/rbs/type_alias_dependency.rb
> +    def direct_dependency(type, result = Set[])
I'm not sure if this definition of `#direct_dependency` allows type definitions like:

```rbs
type a = Array[a]
type b = [b, b]
type c = { foo: c }
type d = ^(d) -> d
```

`#direct_dependency` will test if the type is a union, optional, or intersection and then returns the `#direct_dependency`s of the direct child types.

2021-08-02 09:12 UTC, soutaro commented on lib/rbs/type_alias_dependency.rb
> +      return result if SAFELIST.include?(type.class)
Please write a case analysis using `case-when` here, instead of having `SAFELIST`.

2021-08-02 09:14 UTC, soutaro commented on lib/rbs/type_alias_dependency.rb
> +        @dependencies[name] = {}
```suggestion
        @dependencies[name] = Set[]
```

2021-08-05 15:05 UTC, soutaro approved these changes
Thanks! 👍

2021-08-05 15:05 UTC, merged