Generate RBS from json schema
ruby/rbs pull request #730
Opened 2021-08-05 17:41 UTC by raosush

# Description
- This PR contains changes required to support generation of RBS from JSON schema
- Added `rbs-json-schema` CLI base command for usage
- Created `json-schema` folder with `cli.rb` class & `generator.rb` class which generates RBS

# Example

1. 
![image](https://user-images.githubusercontent.com/57192414/128396188-04e3e1aa-9b2c-4b8b-b159-7a64cd38d44e.png)

2.
![image](https://user-images.githubusercontent.com/57192414/128395970-aa4673ae-e9b6-49e4-af26-d1ccc39a4dc4.png)
![image](https://user-images.githubusercontent.com/57192414/128396064-170d5444-e758-4c9c-8a8e-131aa60de5f0.png)
![image](https://user-images.githubusercontent.com/57192414/128396106-2e0bebe5-31f4-4442-8584-d8b8acf6df54.png)

2021-08-05 17:42 UTC, raosush commented
- [ ] Add signatures for new classes
- [ ] Add tests for new feature

2021-08-08 09:01 UTC, soutaro requested changes
Thank you for the contribution! I post some comments about minor improvements.

The major possible improvement is to refactor `#fetch_type` to accept a `Hash[String, untyped]`, an object representing a type. There are two steps currently, but I feels we can do in one method and the code would be more straightforward.

```json
{ "type": "string" }              // => ::String
{ "type": "string", "enum": ["foo", "bar"] }    // => "foo" | "bar"
{ "$ref": "location.json" }       // => location
{ "type": "array", "item": [{ "type": "integer" }, { "type": "string" }] } // => [Integer, String]

// etc...
```

2021-08-10 09:12 UTC, soutaro commented on lib/rbs/json_schema/generator.rb
> +          schema.dig(SCHEMA_DEFINITIONS[0])&.each do |name, definition|
I don't think using `SCHEMA_DEFINITIONS` constant is good.

* I would simply write a string literal `"definitions"` here
* If you don't want to do that, define constants for each string piece for readability. `DEFINITIONS = "definitions"`

2021-08-10 09:13 UTC, soutaro commented on lib/rbs/json_schema/generator.rb
> +      def fetch_type(type, name: nil, absolute: nil, prefix: true)
It's not clear to me why we need this method. Calling the constructor methods directly would be sufficient?

2021-08-10 09:16 UTC, soutaro commented on lib/rbs/json_schema/generator.rb
> +          # Parse & generate declarations from `definitions` attribute of the schema
The problem is that there is no standard for the `definitions` key.

* https://json-schema.org/understanding-json-schema/structuring.html#ref
* https://json-schema.org/understanding-json-schema/structuring.html#id19

`$defs` would be more standard key...

2021-08-13 14:36 UTC, soutaro requested changes
The overall structure of finding types looks good.
I would like to request relatively minor fixes around the `#translate_type` method.

2021-08-13 14:36 UTC, soutaro commented on lib/rbs/json_schema/generator.rb
> +      SCHEMA_DEFINITIONS = %w(definitions properties type enum const allOf oneOf items $ref $schema title description).freeze
I don't think declarating this constant makes much sense. Writing literals directly is better.

2021-08-13 14:36 UTC, soutaro commented on lib/rbs/json_schema/generator.rb
> +      TypeName = RBS::TypeName
No need to declare `TypeName` and `Namespace`.

2021-08-13 14:36 UTC, soutaro commented on lib/rbs/json_schema/generator.rb
> +        when schema.key?(SCHEMA_DEFINITIONS[3])
The implementation for `enum` type would be something like the following, without `SCHEMA_DEFINITIONS` constant and `fetch_type` method:

```rb
        when values = schema[:enum]
          unless values.is_a?(Array)
            raise ValidationError.new(......)
          end

          types = values.map do |value|
            case value
            when String, Integer
              Types::Literal.new(literal: value, location: nil)
            when nil
              Types::Bases::Nil.new(location: nil)
            else
              raise ......
            end
          end

          type = Types::Union.new(types: types, location: nil)
```

I believe this is short and understandable enough.

2021-08-13 14:36 UTC, soutaro commented on lib/rbs/json_schema/cli.rb
> +          opts.on("-I DIR", "Directory containing a collection of JSON schema from which RBS is to be generated") do |dir|
I think passing file paths or directory paths will work.

```rb
generator = JSONSchema::Generator.new(stringify_keys: true, stdout: stdout, stderr: stderr)

ARGV.each do |arg|
  path = Pathname(arg)

  case
  when path.file?
    generator.generate(URI.parse(path.to_s))
  when path.directory?
    path.children.each do |child|
      generator.generate(URI.parse(child.to_s))
    end
  end
end

generator.write_output
```

2021-08-13 14:36 UTC, soutaro commented on lib/rbs/json_schema/generator.rb
> +          if resolved_uri.path == uri.path
I don't think we should skip generating definitions for other files, but save the declarations included each JSON files in Hash.

```
attr_reader path_decls: Hash[String,AST::Declarations::Module]
```

Then we can group the declarations of each JSON file in the output.

```ruby
# generate_rbs
@path_decls[uri.path].members << decl if !decl.type.nil?
```

2021-08-20 16:39 UTC, soutaro approved these changes
👍

2021-08-21 17:48 UTC, merged