[Net::HTTP] Add timeout errors
ruby/rbs pull request #892
Opened 2022-02-02 13:06 UTC by raosush

# Description
The current `rbs` file for `Net::HTTP` contained only `ProtocolError`s. Hence, this PR adds the missing `Timeout` errors.

# Changes
- Added `timeout` as a dependency, since `OpenTimeout`, `ReadTimeout`, `WriteTimeout` are subclasses of `Timeout::Error`. [Ref](https://github.com/ruby/net-protocol/blob/master/lib/net/protocol.rb#L70-L99)
- The corresponding `Timeout` errors have been added into `net-http.rbs`

Fixes: #843

2022-02-03 02:35 UTC, soutaro commented
Thank you, @raosush !

Could you run `rbs annotate stdlib/net-http` to import the RDoc?

2022-02-04 01:57 UTC, soutaro requested changes
🙏

2022-02-04 02:37 UTC, raosush commented
> Thank you, @raosush !
> 
> Could you run `rbs annotate stdlib/net-http` to import the RDoc?

@soutaro sir, running the annotate command does not annotate the timeout classes since there is not RDoc available for them. Ref: https://ruby-doc.org/stdlib-2.7.1/libdoc/net/pop/rdoc/Net/Protocol.html

2022-02-04 07:25 UTC, soutaro commented
@raosush Could you try again ruby 3.1? (It finds docs on my computer.)

2022-02-04 18:05 UTC, raosush commented
> @raosush Could you try again using ruby 3.1? (It finds docs on my computer.)

@soutaro yes sir. On Ruby 3.1 I was able to fetch RDoc documentation and annotate it.

2022-02-07 07:44 UTC, soutaro approved these changes
Thanks! 🎉

2022-02-07 07:44 UTC, merged