Add method `to_d` (convert into BigDecimal) to some classes
ruby/rbs pull request #936
Opened 2022-03-23 16:57 UTC by takahashim

Target classes: Integer, Float, String, BigDecimal, Rational, Complex and NilClass

2022-03-24 05:40 UTC, ksss reviewed
One way to do it is to create `bigdecimal-util` like `bigdecimal-math`, but RBS seems to be a tool that takes convenience over correctness, so this seems to be the way to go.

2022-03-24 05:40 UTC, ksss commented on stdlib/bigdecimal/0/big_decimal.rbs
> +  #
Maybe `call-seq` is not necessary.
I think you should use the `rbs annotate` tool.

2022-03-28 13:26 UTC, soutaro submitted a review, later dismissed
Could you try copying RDoc using `rbs annotate`?

2022-03-28 13:28 UTC, soutaro requested changes
Could you try copying RDoc using rbs annotate?

2022-03-31 12:40 UTC, soutaro approved these changes
Merging this PR. Will update the docs myself.

2022-03-31 12:41 UTC, merged